#!/usr/bin/env bash
read -p " Enter the apikey : " apikey
#read -p " Enter the MacAddress : " MacAddress
read -p "Enter the Field Name ex vendorDetails (or with subfield) vendorDetails.companyName : " fieldname
#echo $macdetails
#macdetails=$(/usr/bin/curl -Gs "https://api.macaddress.io/v1?apiKey=$apikey&output=json&search=$1")
input="/home/san/test/MacAddress/fname"
while IFS= read -r line
do
	curl -Gs "https://api.macaddress.io/v1?apiKey=$apikey&output=json&search=$1"$line | jq ".$fieldname"
done < "$input"
